export * from "./types";
export * from "./epvFloor";
export * from "./fundamentalsToFloorInput";
export * from "./strikeZone";
export * from "./priceAge";
export * from "./maintenanceCapex";
export * from "./reproductionValue";
export * from "./growthValue";
export { deriveOeDcf, reconcileMethods, pickLatestFredPoint } from "./ownerEarningsDcf";
export { deriveValuationVerdict } from "./deriveValuationVerdict";
export type { ValuationVerdict, VerdictBucket, VerdictCoverage } from "./deriveValuationVerdict";
export { deriveValuationMethods } from "./deriveValuationMethods";
export type { ValuationMethods } from "./deriveValuationMethods";
export { runValuation } from "./runValuation";
export type { RunValuationInput, SuppressedReason, ValuationRun } from "./runValuation";
export { resolveAds } from "./adsNormalization";
export { isFundamentalsStale, FUNDAMENTALS_MAX_AGE_MONTHS } from "./fundamentalsStale";
export { isSplitCoverageStale } from "./splitCoverage";
export { fundamentalsIntegrityViolated } from "./fundamentalsIntegrity";
// 件⑤:控股集团 SOTP 读取侧(个股页与 valuation-ingest 共用同一入口,口径不得分裂)。
export { readHoldcoSotp } from "./holdcoSotpFromDb";
