// 投资人姓氏/基金简称 → 规范 slug 的 301 表（SEO：接住自然搜索与站外链接里的人名 URL，
// 如 /investors/ackman 现状 404）。来源：76 位投资人 person 字段的唯一姓氏
//（人工审查剔除撞名、过短、复合姓）+ 常见基金简称。新增投资人时在此补充。
//
// 消费方：
//  - next.config.ts redirects()：覆盖 /zh/investors/<alias> 与 /en/investors/<alias>（308）
//  - src/proxy.ts：覆盖裸 /investors/<alias>（301；本版 Next 的 redirects 正则强制要求
//    zh|en 前缀段，裸路径永远匹配不到 config 规则，只能由 proxy 在 rewrite 前接住）
// 与 src/lib/investorAliases.ts（搜索关键词表）是两回事，勿合并。
export const INVESTOR_ALIASES: Record<string, string> = {
  ackman: "pershing-square",
  buffett: "berkshire-hathaway",
  munger: "daily-journal",
  klarman: "baupost-group",
  burry: "scion-asset-management",
  tepper: "appaloosa",
  dalio: "bridgewater-associates",
  druckenmiller: "duquesne-family-office",
  einhorn: "greenlight-capital",
  loeb: "third-point",
  marks: "oaktree",
  pabrai: "pabrai-funds",
  watsa: "fairfax",
  smith: "fundsmith",
  rochon: "giverny-capital",
  icahn: "icahn-capital",
  coleman: "tiger-global",
  peltz: "trian-partners",
  hohn: "tci-fund",
  halvorsen: "viking-global",
  mandel: "lone-pine-capital",
  ainslie: "maverick-capital",
  armitage: "egerton-capital",
  sosin: "cas-investment-partners",
  ketterer: "causeway-capital",
  hawkins: "southeastern-asset",
  morfit: "valueact-capital",
  pzena: "pzena-investment",
  romick: "first-pacific-advisors",
  berkowitz: "fairholme",
  greenberg: "brave-warrior",
  cooperman: "cooperman-family-office",
  davis: "davis-advisors",
  dorsey: "dorsey-asset",
  ellenbogen: "durable-capital",
  welling: "engaged-capital",
  russo: "gardner-russo",
  gates: "gates-foundation-trust",
  wachenheim: "greenhaven-associates",
  tarasoff: "greenlea-lane-capital",
  nygren: "harris-associates",
  kahn: "kahn-brothers",
  train: "lindsell-train",
  bancroft: "makaira-partners",
  gayner: "markel",
  katz: "matrix-asset-advisors",
  miller: "miller-value-partners",
  lawrence: "oakcliff-capital",
  olstein: "olstein-capital",
  mclemore: "patient-capital",
  vinall: "rv-capital",
  bloomstran: "semper-augustus",
  hong: "shawspring-partners",
  burn: "sound-shore",
  rolfe: "wedgewood-partners",
  weitz: "weitz-investment",
  fitzpatrick: "vulcan-value-partners",
  abrams: "abrams-capital",
  tangen: "ako-capital",
  akre: "akre-capital",
  spier: "aquamarine-capital",
  rogers: "ariel-investments",
  roepers: "atlantic-investment",
  chou: "chou-associates",
  alexander: "conifer-management",
  duan: "hh-international",
  // 基金简称（站外常用叫法）
  pershing: "pershing-square",
  baupost: "baupost-group",
  berkshire: "berkshire-hathaway",
  bridgewater: "bridgewater-associates",
  sequoia: "ruane-cunniff",
  scion: "scion-asset-management",
  duquesne: "duquesne-family-office",
  himalaya: "himalaya-capital",
  greenlight: "greenlight-capital",
  "li-lu": "himalaya-capital",
  tci: "tci-fund",
  tiger: "tiger-global",
  trian: "trian-partners",
  dodge: "dodge-and-cox",
  tweedy: "tweedy-browne",
};
