// 投资者中文别名 / 搜索关键词(按 manager slug 索引)。
// 用途:中文模式下用户输入「巴菲特」「芒格」等也能命中对应投资者。
// 这是一份精选、人工维护的映射(覆盖当前 34 位收录投资者);新增投资者时在此补充。
// 值为空格分隔的关键词串,搜索时做包含匹配。
export const INVESTOR_ALIASES: Record<string, string> = {
  "berkshire-hathaway": "巴菲特 沃伦巴菲特 伯克希尔",
  "scion-asset-management": "迈克尔伯里 伯里 大空头",
  "pershing-square": "阿克曼 比尔阿克曼 潘兴广场",
  "baupost-group": "克拉曼 塞斯克拉曼",
  "duquesne-family-office": "德鲁肯米勒 杜肯",
  "daily-journal": "芒格 查理芒格",
  "fundsmith": "特里史密斯 史密斯",
  "akre-capital": "阿克尔 查克阿克尔",
  "markel": "盖纳 托马斯盖纳 马克尔",
  "pabrai-funds": "帕伯莱 莫尼什帕伯莱",
  "himalaya-capital": "李录 喜马拉雅",
  "valley-forge-capital": "坎特萨里亚",
  "giverny-capital": "罗琼 弗朗索瓦罗琼",
  "polen-capital": "普伦资本",
  "weitz-investment": "韦茨 华莱士韦茨",
  "semper-augustus": "布卢姆斯特兰",
  "brave-warrior": "格林伯格 格伦格林伯格",
  "fairholme": "伯科威茨 布鲁斯伯科威茨",
  "yacktman": "雅克曼",
  "harris-associates": "奈格伦 比尔奈格伦 哈里斯",
  "dodge-and-cox": "道奇考克斯 道奇与考克斯",
  "ruane-cunniff": "红杉 鲁安 塞阔亚 Sequoia",
  "tweedy-browne": "特威迪布朗",
  "greenlight-capital": "艾因霍恩 大卫艾因霍恩 绿光资本",
  "third-point": "勒布 丹尼尔勒布 第三点",
  "appaloosa": "泰珀 大卫泰珀",
  "icahn-capital": "伊坎 卡尔伊坎",
  "tci-fund": "霍恩 克里斯霍恩",
  "fairfax": "沃萨 普雷姆沃萨 加拿大巴菲特 费尔法克斯",
  "oaktree": "马克斯 霍华德马克斯 橡树资本",
  "gates-foundation-trust": "盖茨 比尔盖茨 盖茨基金会",
  "dorsey-asset": "多西 帕特多西",
  "hh-international": "段永平",
  "bridgewater-associates": "达利欧 瑞达利欧 桥水 桥水基金",
};
