from datetime import datetime, timezone

NOW = datetime.now(timezone.utc).isoformat()

SECTIONS = {
    "overall-regime": {
        "title": "Overall Regime",
        "title_zh": "总体流动性状态",
        "freshness_status": "mock",
        "data_date": "2026-05-29",
        "summary": "Mock dashboard state for deployment skeleton validation.",
        "summary_zh": "用于验证部署骨架的模拟仪表盘状态。",
        "key_metrics": [
            {"label": "Liquidity Bias", "label_zh": "流动性倾向", "value": "Neutral", "unit": ""},
            {"label": "Funding Stress", "label_zh": "融资压力", "value": "Low", "unit": ""},
            {"label": "Data Mode", "label_zh": "数据模式", "value": "Mock only", "unit": ""},
        ],
        "signals": [
            "No real NY Fed feeds connected yet.",
            "No trading recommendations are generated.",
        ],
    },
    "repo-financing": {
        "title": "Repo Financing",
        "title_zh": "回购融资",
        "freshness_status": "mock",
        "data_date": "2026-05-29",
        "summary": "Synthetic repo snapshot for UI and API contract testing.",
        "summary_zh": "用于 UI 与 API 合约测试的模拟回购数据。",
        "key_metrics": [
            {"label": "SOFR", "label_zh": "SOFR", "value": "5.31", "unit": "%"},
            {"label": "Tri-party Volume", "label_zh": "三方回购规模", "value": "1.95", "unit": "tn USD"},
        ],
        "signals": ["Mock repo values only.", "Refresh endpoint updates status metadata only."],
    },
    "dealer-inventory": {
        "title": "Dealer Inventory",
        "title_zh": "一级交易商库存",
        "freshness_status": "mock",
        "data_date": "2026-05-29",
        "summary": "Placeholder dealer inventory metrics for layout validation.",
        "summary_zh": "用于布局验证的一级交易商库存占位指标。",
        "key_metrics": [
            {"label": "Treasury Net Position", "label_zh": "美债净持仓", "value": "284", "unit": "bn USD"},
            {"label": "Duration Tilt", "label_zh": "久期倾向", "value": "Balanced", "unit": ""},
        ],
        "signals": ["Real primary dealer data will be added in a later rebuild step."],
    },
    "transactions": {
        "title": "Transactions and Liquidity",
        "title_zh": "成交与流动性 Transactions / Liquidity",
        "freshness_status": "mock",
        "data_date": "2026-05-29",
        "summary": "Placeholder transactions metrics for layout validation.",
        "summary_zh": "用于布局验证的成交活动占位指标。",
        "key_metrics": [
            {"label": "Latest Level", "label_zh": "最新水平 Latest Level", "value": "Mock only", "unit": ""},
            {"label": "Activity Direction", "label_zh": "成交方向 Activity Direction", "value": "Mock only", "unit": ""},
        ],
        "signals": ["Real transactions data will be added in a later rebuild step."],
    },
    "fails": {
        "title": "Fails and Specialness",
        "title_zh": "结算失败 Fails / Specialness",
        "freshness_status": "mock",
        "data_date": "2026-05-29",
        "summary": "Placeholder fails metrics for layout validation.",
        "summary_zh": "用于布局验证的 fails 占位指标。",
        "key_metrics": [
            {"label": "Latest Fails Measure", "label_zh": "最新 fails 指标 Latest Fails Measure", "value": "Mock only", "unit": ""},
            {"label": "Fails Direction", "label_zh": "Fails 方向 Fails Direction", "value": "Mock only", "unit": ""},
        ],
        "signals": ["Real fails data will be added in a later rebuild step."],
    },
    "market-share": {
        "title": "Market Share",
        "title_zh": "市场份额",
        "freshness_status": "mock",
        "data_date": "2026-05-29",
        "summary": "Mock primary dealer market share section.",
        "summary_zh": "模拟一级交易商市场份额模块。",
        "key_metrics": [
            {"label": "Top Dealer Share", "label_zh": "头部交易商份额", "value": "18.4", "unit": "%"},
            {"label": "Concentration", "label_zh": "集中度", "value": "Stable", "unit": ""},
        ],
        "signals": ["For dashboard navigation only."],
    },
    "auction-risk": {
        "title": "Auction Calendar and Auction Risk",
        "title_zh": "拍卖风险 Auction Risk",
        "freshness_status": "Unavailable",
        "data_date": None,
        "expected_update_frequency": "daily",
        "summary": "Auction data is not connected yet.",
        "summary_zh": "拍卖模块尚未接入真实数据。",
        "interpretation": "Auction data is unavailable.",
        "interpretation_zh": "拍卖数据当前不可用。",
        "why_it_matters": "Treasury auctions are a primary channel for new supply.",
        "why_it_matters_zh": "Treasury auction 是新增供给进入市场的重要渠道。",
        "key_metrics": [
            {"label": "Auction Risk", "label_zh": "拍卖风险 Auction Risk", "value": "Unavailable", "unit": ""},
            {"label": "Upcoming 14-day Supply", "label_zh": "未来14天供给 Upcoming 14-day Supply", "value": "Unavailable", "unit": ""},
        ],
        "signals": ["Awaiting live Treasury auction connection."],
        "warnings": ["Auction data unavailable."],
        "last_refreshed_at": NOW,
    },
    "soma": {
        "title": "SOMA and Balance Sheet Pressure",
        "title_zh": "美联储持仓 SOMA",
        "freshness_status": "Unavailable",
        "data_date": None,
        "expected_update_frequency": "weekly",
        "summary": "SOMA holdings are not connected yet.",
        "summary_zh": "SOMA 持仓模块尚未接入真实数据。",
        "interpretation": "SOMA data is unavailable.",
        "interpretation_zh": "SOMA 数据当前不可用。",
        "why_it_matters": "SOMA changes help assess Fed duration absorption.",
        "why_it_matters_zh": "SOMA 变化有助于观察 Fed 是否仍在吸收 duration。",
        "key_metrics": [
            {"label": "Latest Treasury Holdings", "label_zh": "最新 Treasury 持仓 Latest Treasury Holdings", "value": "Unavailable", "unit": ""},
            {"label": "Latest MBS Holdings", "label_zh": "最新 MBS 持仓 Latest MBS Holdings", "value": "Unavailable", "unit": ""},
            {"label": "Total SOMA 4-week Change", "label_zh": "SOMA 4周变化 Total SOMA 4-week Change", "value": "Unavailable", "unit": ""},
        ],
        "signals": ["Awaiting real NY Fed SOMA connection."],
        "warnings": ["SOMA data unavailable."],
        "normalized_data": [],
        "last_refreshed_at": NOW,
    },
    "reference-rates": {
        "title": "Reference Rates and Funding Conditions",
        "title_zh": "短端利率 Reference Rates",
        "freshness_status": "Unavailable",
        "data_date": None,
        "expected_update_frequency": "daily",
        "summary": "Reference rates are not connected yet.",
        "summary_zh": "短端利率模块尚未接入真实数据。",
        "interpretation": "Reference rate data is unavailable.",
        "interpretation_zh": "短端利率数据当前不可用。",
        "why_it_matters": "Short-term reference rates help monitor money-market funding conditions.",
        "why_it_matters_zh": "短端利率是判断资金市场是否紧张的核心指标。",
        "key_metrics": [
            {"label": "SOFR-EFFR", "label_zh": "SOFR-EFFR", "value": "Unavailable", "unit": ""},
            {"label": "OBFR-EFFR", "label_zh": "OBFR-EFFR", "value": "Unavailable", "unit": ""},
            {"label": "TGCR-SOFR", "label_zh": "TGCR-SOFR", "value": "Unavailable", "unit": ""},
            {"label": "BGCR-SOFR", "label_zh": "BGCR-SOFR", "value": "Unavailable", "unit": ""},
            {
                "label": "Funding Rate Stress",
                "label_zh": "融资利率压力 Funding Rate Stress",
                "value": "Unavailable",
                "unit": "",
            },
        ],
        "signals": ["Awaiting real NY Fed Reference Rates connection."],
        "warnings": ["Reference Rates data unavailable."],
        "normalized_data": [],
        "spreads_bps": {},
        "last_refreshed_at": NOW,
    },
    "policy-expectations": {
        "title": "Policy Expectations and FOMC Risk",
        "title_zh": "政策预期 Policy Expectations",
        "freshness_status": "Missing",
        "data_date": None,
        "expected_update_frequency": "manual",
        "summary": "Policy Expectations data unavailable until a manual SME file is added.",
        "summary_zh": "在手动放入 SME 文件之前，Policy Expectations 数据不可用。",
        "interpretation": "Policy expectations data is unavailable until a manual SME file is loaded.",
        "interpretation_zh": "在手动导入 SME 文件之前，政策预期模块当前不可用。",
        "why_it_matters": "Survey-based policy expectations help show whether economists expect easing, steady policy, or a firmer policy path.",
        "why_it_matters_zh": "政策预期可以帮助判断市场是否预期降息、按兵不动，或更偏紧的政策路径。",
        "key_metrics": [
            {"label": "SME Release Date", "label_zh": "SME 发布时间 SME Release Date", "value": "Unavailable", "unit": ""},
            {"label": "Latest Fed Funds Median", "label_zh": "最新联邦基金利率中位数 Latest Fed Funds Median", "value": "Unavailable", "unit": ""},
            {"label": "Policy Expectations Risk", "label_zh": "政策预期风险 Policy Expectations Risk", "value": "Unavailable", "unit": ""},
        ],
        "signals": ["Manual SME file has not been added yet."],
        "warnings": ["Policy Expectations data unavailable."],
        "last_refreshed_at": NOW,
    },
    "facility-usage": {
        "title": "Money Market Facilities: ON RRP and SRP",
        "title_zh": "资金工具 ON RRP / SRP",
        "freshness_status": "Unavailable",
        "data_date": None,
        "expected_update_frequency": "daily",
        "summary": "Facility usage data unavailable.",
        "summary_zh": "Facility usage 数据当前不可用。",
        "interpretation": "Facility usage data unavailable.",
        "interpretation_zh": "Facility usage 数据当前不可用。",
        "why_it_matters": "Facility usage helps distinguish between high repo financing usage and actual demand for Fed backstop liquidity.",
        "why_it_matters_zh": "这些工具的使用情况有助于区分 repo financing 使用量偏高与真正需要 Fed 流动性支持之间的差别。",
        "key_metrics": [
            {"label": "ON RRP Latest Usage", "label_zh": "ON RRP 最新使用量 ON RRP Latest Usage", "value": "Unavailable", "unit": ""},
            {"label": "Facility Usage Signal", "label_zh": "资金工具信号 Facility Usage Signal", "value": "Unavailable", "unit": ""},
        ],
        "signals": ["Awaiting live facility-usage connection."],
        "warnings": ["Facility usage data unavailable."],
        "last_refreshed_at": NOW,
    },
    "data-freshness": {
        "title": "Data Freshness",
        "title_zh": "数据新鲜度",
        "freshness_status": "mock",
        "data_date": "2026-05-29",
        "summary": "All sections are running in mock-data mode.",
        "summary_zh": "所有模块当前均为模拟数据模式。",
        "key_metrics": [
            {"label": "Connected Feeds", "label_zh": "已连接数据源", "value": "0", "unit": ""},
            {"label": "Mock Sections", "label_zh": "模拟模块", "value": "12", "unit": ""},
        ],
        "signals": ["Expected in first rebuild.", "No live-source freshness checks yet."],
    },
}

REFRESH_STATUS = {
    "state": "idle",
    "last_started_at": None,
    "last_finished_at": None,
    "message": "Mock refresh service is ready.",
}
